server:
  port: 8081
  servlet:
    contextPath: /mash

spring:
  datasource:
     #url: jdbc:postgresql://localhost:5432/postgres
     #username: postgres
     #password: postgres
     url: jdbc:mysql://localhost:3306/mash
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Mash
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        #dialect: org.hibernate.dialect.PostgreSQL95Dialect
        dialect: org.hibernate.dialect.MySQL5Dialect